<svg width="800" height="200">
  <!-- Background -->
  <rect width="100%" height="100%" fill="#0D1117"/>
  
  <!-- Pacman (bagian atas) -->
  <g transform="translate(0,50)">
    <circle cx="0" cy="0" r="15" fill="yellow">
      <animate attributeName="cx" from="0" to="800" dur="10s" repeatCount="indefinite"/>
    </circle>
  </g>
  
  <!-- Snake (bagian bawah) -->
  <g transform="translate(0,150)">
    <rect x="0" y="-10" width="20" height="20" fill="green">
      <animate attributeName="x" from="0" to="800" dur="15s" repeatCount="indefinite" begin="2s"/>
    </rect>
  </g>
</svg>
